### ISSUE TITLE
我用qt编译有很多警告不过没有error，但运行就崩溃

### ISSUE THREAD

**Issue by rangercyh** [LuyaooChen/BackgroundMattingTool#1]
![image](https://user-images.githubusercontent.com/1217541/133051664-145ce051-c1a0-4bb3-9df1-6dcd3644428d.png)

调试发现BgMatting构造抛出异常，不知道作者有没有遇到过

**Comment by rangercyh** [comment]
编译器用的是msvc2019，不知道能不能行
![image](https://user-images.githubusercontent.com/1217541/133052377-501df4f6-2b1f-4633-b619-2de4592dc758.png)

**Comment by LuyaooChen** [comment]
Torch我记得就是会有很多警告，然后也确实很容易崩溃。。
我也用得是msvc2019，应该不是编译器和环境的问题。

具体什么原因不好说。。好像没遇到过在这个地方崩溃的
可以尝试一下使用vs打开运行工程（vs有个qt插件），vs的报错似乎会详细一些。
或者下载我编译好的release看看能否运行？。

**Comment by rangercyh** [comment]
试了下vs，报错信息有了，但还是在同样的地方崩溃了，汗。。
![image](https://user-images.githubusercontent.com/1217541/133087872-a6e3f674-ac98-42cf-afbb-2364552fb30d.png)

**Comment by LuyaooChen** [comment]
有点奇怪，我这里是没问题的。。
你把初始化的语句删掉，device直接赋值为`device = torch::Device("cpu");`试试？
其实cpu版本的话，你把有关device的语句都删掉也应该是可以的，本来是为了cuda准备的

**Comment by rangercyh** [comment]
试了下，还是不太行，能够详细说下用的libtorch是1.8.1的哪个版本吗？是带cuda的102还是111的？release的还是debug的？我再试试

**Comment by LuyaooChen** [comment]
我测试的版本是cpu release版本

**Comment by rangercyh** [comment]
终于搞定了。。。。一定要用1.8.1的cuda111的release版本才可以，谢谢

**Comment by LuyaooChen** [comment]
你是用cuda还是cpu跑？好奇是什么原因

**Comment by rangercyh** [comment]
> 你是用cuda还是cpu跑？好奇是什么原因

我就用的cpu跑，但是貌似一定需要cuda的版本才可以，纯cpu的那个版本我死活链接不成功。。没有深究原因
